// // File generated by FlutterFire CLI.
// // ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.

// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for windows - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyDntOBtJbombsj_STRN1TSCXhNf-vGgE28',
//     appId: '1:1013441484355:web:2d95aa07e4fb769d1ea6f6',
//     messagingSenderId: '1013441484355',
//     projectId: 'psycholist-appointment-app',
//     authDomain: 'psycholist-appointment-app.firebaseapp.com',
//     storageBucket: 'psycholist-appointment-app.appspot.com',
//     measurementId: 'G-DH1Q6H1RY9',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyD61SLAEpDHVTTTchqr-ySPSaOqViUapcA',
//     appId: '1:1013441484355:android:f2f0f7533ffea6bf1ea6f6',
//     messagingSenderId: '1013441484355',
//     projectId: 'psycholist-appointment-app',
//     storageBucket: 'psycholist-appointment-app.appspot.com',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyAs0sC7V8LZ518Wtc0Iys18AJRMv-hlZUQ',
//     appId: '1:1013441484355:ios:c5eb1284fbc978c21ea6f6',
//     messagingSenderId: '1013441484355',
//     projectId: 'psycholist-appointment-app',
//     storageBucket: 'psycholist-appointment-app.appspot.com',
//     iosClientId: '1013441484355-avr6ndsg8pir9g07gih50ddbj777480k.apps.googleusercontent.com',
//     iosBundleId: 'com.example.psychologistAppointment',
//   );

//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyAs0sC7V8LZ518Wtc0Iys18AJRMv-hlZUQ',
//     appId: '1:1013441484355:ios:c5eb1284fbc978c21ea6f6',
//     messagingSenderId: '1013441484355',
//     projectId: 'psycholist-appointment-app',
//     storageBucket: 'psycholist-appointment-app.appspot.com',
//     iosClientId: '1013441484355-avr6ndsg8pir9g07gih50ddbj777480k.apps.googleusercontent.com',
//     iosBundleId: 'com.example.psychologistAppointment',
//   );
// }
